// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'book_info.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$BookInfoImpl _$$BookInfoImplFromJson(Map<String, dynamic> json) =>
    _$BookInfoImpl(
      authorName: json['authorName'] as String?,
      authorSort: json['authorSort'] as String?,
      bookshelfId: json['bookshelfId'] as String?,
      categoryNo: json['categoryNo'] as String?,
      contentsType: json['contentsType'] as String?,
      description: json['description'] as String?,
      downloadDate: json['downloadDate'] as String?,
      drmSellerSeq: json['drmSellerSeq'] as String?,
      drmType: json['drmType'] as String?,
      ebookCode: json['ebookCode'] as String?,
      ebookId: json['ebookId'] as String?,
      editAnnotationDate: json['editAnnotationDate'] as String?,
      favorite: json['favorite'] as String?,
      fileSize: json['fileSize'] as String?,
      language: json['language'] as String?,
      lastReadCFI: json['lastReadCFI'] as String?,
      lastReadCFIOffset: json['lastReadCFIOffset'] as String?,
      lastReadDate: json['lastReadDate'] as String?,
      lastReadFileIndex: json['lastReadFileIndex'] as String?,
      lastReadOffset: json['lastReadOffset'] as String?,
      lastReadPercent: json['lastReadPercent'] as String?,
      lastReadPosType: json['lastReadPosType'] as String?,
      lastReadSeq: json['lastReadSeq'] as String?,
      lastReadUpdateDate: json['lastReadUpdateDate'] as String?,
      lastReadXPath: json['lastReadXPath'] as String?,
      lastUpdateDate: json['lastUpdateDate'] as String?,
      lockPW: json['lockPW'] as String?,
      orderDate: json['orderDate'] as String?,
      orderDetailSeq: json['orderDetailSeq'] as String?,
      orderSeq: json['orderSeq'] as String?,
      parentCode: json['parentCode'] as String?,
      productCode: json['productCode'] as String?,
      productType: json['productType'] as String?,
      publishingName: json['publishingName'] as String?,
      rating: json['rating'] as String?,
      readDirection: json['readDirection'] as String?,
      rentEndDate: json['rentEndDate'] as String?,
      rentPeriod: json['rentPeriod'] as String?,
      rentStartDate: json['rentStartDate'] as String?,
      saleType: json['saleType'] as String?,
      savePath: json['savePath'] as String?,
      sellerOrderCd: json['sellerOrderCd'] as String?,
      seq: json['seq'] as String?,
      serialNumber: json['serialNumber'] as String?,
      seriesCode: json['seriesCode'] as String?,
      statusCd: json['statusCd'] as String?,
      storeId: json['storeId'] as String?,
      thumbnailPath: json['thumbnailPath'] as String?,
      thumbnailUrl: json['thumbnailUrl'] as String?,
      title: json['title'] as String?,
      titleSort: json['titleSort'] as String?,
      uniqueId: json['uniqueId'] as String?,
      userId: json['userId'] as String?,
      userNo: json['userNo'] as String?,
      readDone: json['readDone'] as String?,
      pageMode: json['pageMode'] as String?,
      fitmode: json['fitmode'] as String?,
      theme: json['theme'] as String?,
      managedId: json['managedId'] as int?,
      bookAnnotationCounts: json['bookAnnotationCounts'] as int?,
    );

Map<String, dynamic> _$$BookInfoImplToJson(_$BookInfoImpl instance) =>
    <String, dynamic>{
      'authorName': instance.authorName,
      'authorSort': instance.authorSort,
      'bookshelfId': instance.bookshelfId,
      'categoryNo': instance.categoryNo,
      'contentsType': instance.contentsType,
      'description': instance.description,
      'downloadDate': instance.downloadDate,
      'drmSellerSeq': instance.drmSellerSeq,
      'drmType': instance.drmType,
      'ebookCode': instance.ebookCode,
      'ebookId': instance.ebookId,
      'editAnnotationDate': instance.editAnnotationDate,
      'favorite': instance.favorite,
      'fileSize': instance.fileSize,
      'language': instance.language,
      'lastReadCFI': instance.lastReadCFI,
      'lastReadCFIOffset': instance.lastReadCFIOffset,
      'lastReadDate': instance.lastReadDate,
      'lastReadFileIndex': instance.lastReadFileIndex,
      'lastReadOffset': instance.lastReadOffset,
      'lastReadPercent': instance.lastReadPercent,
      'lastReadPosType': instance.lastReadPosType,
      'lastReadSeq': instance.lastReadSeq,
      'lastReadUpdateDate': instance.lastReadUpdateDate,
      'lastReadXPath': instance.lastReadXPath,
      'lastUpdateDate': instance.lastUpdateDate,
      'lockPW': instance.lockPW,
      'orderDate': instance.orderDate,
      'orderDetailSeq': instance.orderDetailSeq,
      'orderSeq': instance.orderSeq,
      'parentCode': instance.parentCode,
      'productCode': instance.productCode,
      'productType': instance.productType,
      'publishingName': instance.publishingName,
      'rating': instance.rating,
      'readDirection': instance.readDirection,
      'rentEndDate': instance.rentEndDate,
      'rentPeriod': instance.rentPeriod,
      'rentStartDate': instance.rentStartDate,
      'saleType': instance.saleType,
      'savePath': instance.savePath,
      'sellerOrderCd': instance.sellerOrderCd,
      'seq': instance.seq,
      'serialNumber': instance.serialNumber,
      'seriesCode': instance.seriesCode,
      'statusCd': instance.statusCd,
      'storeId': instance.storeId,
      'thumbnailPath': instance.thumbnailPath,
      'thumbnailUrl': instance.thumbnailUrl,
      'title': instance.title,
      'titleSort': instance.titleSort,
      'uniqueId': instance.uniqueId,
      'userId': instance.userId,
      'userNo': instance.userNo,
      'readDone': instance.readDone,
      'pageMode': instance.pageMode,
      'fitmode': instance.fitmode,
      'theme': instance.theme,
      'managedId': instance.managedId,
      'bookAnnotationCounts': instance.bookAnnotationCounts,
    };
